apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-back-tomcat-pvc
  namespace: back-end
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-back-tomcat-stgc
  resources:
    requests:
      storage: 5Gi
