apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-front-nginx-pv
  namespace: front-end
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-front-nginx-stgc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-01d2947fba2fde806
