apiVersion: v1
kind: PersistentVolume
metadata:
  name: eks-pm-pv
  namespace: prometheus
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: eks-pm-stg
  csi:
    driver: efs.csi.aws.com
