apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-hpa-back-tomcat
  namespace: test-hpa-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-hpa-back-tomcat
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
