apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back-tomcat-deploy
  name: back-tomcat-deploy
  namespace: back-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back-tomcat-deploy
  template:
    metadata:
      labels:
        app: back-tomcat-deploy
    spec:
      containers:
      - image: public.ecr.aws/e6m3e0t8/h1998yc:tomcat_redis3
        name: tomcat
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        volumeMounts:
        - name: efs-back-storage
          mountPath: /usr/local/tomcat/webapps/ROOT/back-end
      volumes:
      - name: efs-back-storage
        persistentVolumeClaim:
          claimName: efs-back-tomcat-pvc
