apiVersion: v1
kind: Service
metadata:
  labels:
    app: back-tomcat-deploy
  name: back-tomcat-svc
  namespace: back-end
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: back-tomcat-deploy
  type: ClusterIP
  clusterIP: 172.20.20.20
status:
  loadBalancer: {}
